// src/api/endpoints.ts

export const API_ENDPOINTS = {
  DASHBOARD: {
    LAYOUT: "/dashboard/layout",
    LAYOUT_RESET: "/dashboard/layout/reset",
    LAYOUT_DEFAULT: "/dashboard/layout/default",
    PRESETS: "/dashboard/presets",
    PRESET: (presetId: string) => `/dashboard/presets/${presetId}`,
    PRESET_APPLY: (presetId: string) => `/dashboard/presets/${presetId}/apply`,
  },
  CONNECTORS: "/connectors",
  PIPELINES: "/pipelines",
  PIPELINE_EXECUTIONS: "/pipelines/executions",
  PIPELINE_EXECUTION_RETRY: {
    FROM_CURRENT: (id: string) => `/pipelines/executions/${id}/retry?type=from_current`,
    FROM_START: (id: string) => `/pipelines/executions/${id}/retry?type=from_start`,
    BASE: (id: string) => `/pipelines/executions/${id}/retry`,
  },
  SEARCH: "/search",
  SEARCH_CONNECTORS: "/search/connectors",
  ASSETS: {
    GET: (id: string) => `/assets/${id}`,
    DELETE: (id: string) => `/assets/${id}`,
    RENAME: (id: string) => `/assets/${id}/rename`,
    VIEW: (id: string) => `/assets/${id}/view`,
    UPLOAD: "/assets/upload",
    BULK_DOWNLOAD: "/assets/download/bulk",
    BULK_DOWNLOAD_USER_JOBS: "/assets/download/bulk/user",
    BULK_DOWNLOAD_DELETE: (jobId: string) => `/assets/download/bulk/${jobId}`,
    BATCH_DELETE: "/assets/batch",
    BATCH_DELETE_USER_JOBS: "/assets/batch/user",
    BATCH_DELETE_CANCEL: (jobId: string) => `/assets/batch/${jobId}/cancel`,
  },
  USERS: "/settings/users",
  USER: "/users",
  ROLES: "/settings/roles",

  API_KEYS: {
    BASE: "/settings/api-keys",
    GET: (id: string) => `/settings/api-keys/${id}`,
    UPDATE: (id: string) => `/settings/api-keys/${id}`,
    DELETE: (id: string) => `/settings/api-keys/${id}`,
    PERMISSIONS: (id: string) => `/settings/api-keys/${id}/permissions`,
  },
  GROUPS: {
    BASE: "/groups",
    GET: (id: string) => `/groups/${id}`,
    UPDATE: (id: string) => `/groups/${id}`,
    DELETE: (id: string) => `/groups/${id}`,
    ADD_MEMBERS: (id: string) => `/groups/${id}/members`,
    REMOVE_MEMBER: (groupId: string, userId: string) => `/groups/${groupId}/members/${userId}`,
  },

  GROUP_PERMISSIONS: {
    GET: (groupId: string) => `/groups/${groupId}/permissions`,
    UPDATE: (groupId: string) => `/groups/${groupId}/permissions`,
  },

  DISABLE_USER: (userId: string) => `/users/${userId}/disable`,
  ENABLE_USER: (userId: string) => `/users/${userId}/enable`,
  SYSTEM_SETTINGS: {
    GET: "/settings/system",
    SEARCH: "/settings/system/search",
  },
  FAVORITES: {
    BASE: "/users/favorites",
    DELETE: (itemType: string, itemId: string) => `/users/favorites/${itemType}/${itemId}`,
  },
  COLLECTIONS: {
    BASE: "/collections",
    COLLECTION_TYPES: "/collections/collection-types",
    USERS: "/collections/users",
    GET: (id: string) => `/collections/${id}`,
    UPDATE: (id: string) => `/collections/${id}`,
    DELETE: (id: string) => `/collections/${id}`,
    ANCESTORS: (id: string) => `/collections/${id}/ancestors`,
    SHARE: (id: string) => `/collections/${id}/share`,
    UNSHARE: (id: string, userId: string) => `/collections/${id}/share/${userId}`,
    SHARES: (id: string) => `/collections/${id}/share`,
    SHARED_WITH_ME: "/collections/shared-with-me",
    SHARED_BY_ME: "/collections/shared-by-me",
    ITEMS: (id: string) => `/collections/${id}/items`,
    ASSETS: (id: string) => `/collections/${id}/assets`,
    THUMBNAIL: (id: string) => `/collections/${id}/thumbnail`,
  },
  COLLECTION_TYPES: {
    BASE: "/settings/collection-types",
    GET: (id: string) => `/settings/collection-types/${id}`,
    UPDATE: (id: string) => `/settings/collection-types/${id}`,
    DELETE: (id: string) => `/settings/collection-types/${id}`,
    MIGRATE: (id: string) => `/settings/collection-types/${id}/migrate`,
  },
};
